# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ddv <- function(xx, v) {
    .Call(`_gee1step_ddv`, xx, v)
}

dv <- function(xx, adj) {
    .Call(`_gee1step_dv`, xx, adj)
}

dvm <- function(xx, adj) {
    .Call(`_gee1step_dvm`, xx, adj)
}

